model_args:
    model_name: 'Conv3D'
    log_dir: '/home/serfani/serfani_data1/snapshots'
    in_channels: 5
    out_channels: 1
    kernel_size: [2, 3, 3]
    epochs: 50
    learning_rate: 0.001
    weight_decay: 0.0001
    
data_args:
    data_name: 'E33OMA90D'
    species: 'bcb'
    batch_size: 4
    sequence_length: 48
    num_workers: 4
    size: [32, 32]
    padding: [0, 0]