model_args:
    model_name: 'SAConvLSTM'
    log_dir: '/home/serfani/serfani_data1/snapshots'
    in_channels: 5
    out_channels: 1
    encoder_channels: [64, 32, 16]
    kernel_size: [5, 3, 3]
    epochs: 100
    learning_rate: 0.001
    weight_decay: 0.0005
    
data_args:
    data_name: 'E33OMA'
    species: 'bcb'
    batch_size: 4
    sequence_length: 48
    num_workers: 4
    size: [90, 144]
    padding: [35, 8]