model_args:
    model_name: 'SimVP'
    log_dir: '/home/serfani/serfani_data1/snapshots'
    spatio_kernel_enc: 3
    spatio_kernel_dec: 3
    hid_S: 32
    hid_T: 256
    N_T: 8
    N_S: 2
    epochs: 200
    learning_rate: 0.001
    weight_decay: 0.001
    
data_args:
    data_name: 'E33OMA'
    species: 'bcb'
    batch_size: 16
    steps_per_epoch: 986
    sequence_length: 48
    num_workers: 4
    size: [90, 144]
    padding: [35, 8]